apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: box0
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["sleep 30; touch /tmp/debug; sleep 30; rm /tmp/debug"]
