apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis01
  name: redis01
  namespace: finance
spec:
  containers:
  - image: redis
    name: redis01
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
