apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis01
    tier: db
  name: redis02
  namespace: finance
spec:
  containers:
  - image: redis:alpine
    name: redis01
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
